codecov:
  token: c3b231db-2db3-4560-a477-6edcf4cf5ad1
  branch: master
  bot: qcodes-bot
  
coverage:
  precision: 2
  round: down
  range: "80...100"

  notify:
    slack:
      default:
        url: http://qcodes.slack.com
        attachments: "sunburst, diff"


  status:
    project:
      default:
        target: auto

    patch:
      default:
        target: auto


    changes:
      default:


comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
