name: pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release/*'
  merge_group:
    branches: ['main']

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
    - uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc  # v2.0.1
