name: Upload Python Package

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi-release-env
    permissions:
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.12'
    - name: Install build deps
      run: pip install --upgrade pip setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Install Twine
      run: pip install twine
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1
