name: Upload Python Package

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi-release-env
    permissions:
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11'
    - name: Install build deps
      run: pip install --upgrade pip setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Install Twine
      run: pip install twine
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
